-- Drop previous tables if they exist to start fresh with new simplified schema
drop table if exists public.settings;
drop table if exists public.reports;
drop table if exists public.profiles;

-- 1. Profiles Table (Simple Custom Auth)
-- Stores User Creds + Personal Info + Settings (Logo)
create table public.profiles (
  id uuid default gen_random_uuid() primary key,
  username text unique not null,
  password text not null, -- Storing plainly as requested for simplicity
  name text,
  crfa text,
  logo_url text, -- Merged settings
  created_at timestamptz default now()
);

-- Disable RLS so the app can query this table directly for login
alter table public.profiles disable row level security;

-- 2. Reports Table
create table public.reports (
  id bigint generated by default as identity primary key,
  created_by uuid references public.profiles(id) not null,
  identification jsonb not null default '{}'::jsonb,
  history jsonb not null default '[]'::jsonb,
  results jsonb not null default '[]'::jsonb,
  conclusion text,
  recommendations jsonb not null default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Disable RLS so logged in users (managed by app) can read/write
alter table public.reports disable row level security;
